// <auto-generated />
using System;
using Company.DAL.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company.DAL.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20230909171213_UserNameFix")]
    partial class UserNameFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Company.DAL.Data.Models.Auth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("StaffMemberId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StaffMemberId");

                    b.ToTable("Auths");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "123456789",
                            StaffMemberId = 1,
                            UserName = "fouad.abdelhady"
                        },
                        new
                        {
                            Id = 2,
                            Password = "123456789",
                            StaffMemberId = 2,
                            UserName = "ahmed.abdelhady"
                        });
                });

            modelBuilder.Entity("Company.DAL.Data.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "fouad.abdelhady@egabi.com",
                            FullName = "Fouad Abdelhady Fouad",
                            Image = new byte[0],
                            Role = "Manager",
                            Salary = 40000.5m
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "ahmed.abdelhady@egabi.com",
                            FullName = "Ahmed Abdelhady Fouad",
                            Image = new byte[0],
                            ManagerId = 1,
                            Role = "Employee",
                            Salary = 4000.5m
                        });
                });

            modelBuilder.Entity("Company.DAL.Data.Models.Auth", b =>
                {
                    b.HasOne("Company.DAL.Data.Models.Staff", "StaffMember")
                        .WithMany()
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("Company.DAL.Data.Models.Staff", b =>
                {
                    b.HasOne("Company.DAL.Data.Models.Staff", "Manager")
                        .WithMany("TeamMembers")
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Company.DAL.Data.Models.Staff", b =>
                {
                    b.Navigation("TeamMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
